import ComponentDetail from './component/ComponentDetail.vue'
import ComponentMenu from './component/ComponentMenu.vue'
import StoreInfo from './component/StoreInfo.vue'
import BrandDetail from './brand/BrandDetail.vue'
import CategoriesList from './brand/CategoriesList.vue'
import BrandComponent from './brand/BrandComponent.vue'
import OriginalDetail from './original/OriginalDetail.vue'
import Recommends from './Recommends.vue'
import BrandList from './BrandList.vue'
import KindBox from './KindBox.vue'
import CategroyNav from './CategoryNav.vue'
import CategoryProperty from './CategoryProperty.vue'
import ComponentGoods from './ComponentGoods.vue'

export { ComponentDetail, ComponentMenu, StoreInfo, BrandDetail, CategoriesList, BrandComponent, OriginalDetail, Recommends, BrandList, KindBox, CategroyNav, CategoryProperty, ComponentGoods }
